[package]
name = "地图着色"
version = "0.1.0"
authors = ["godcrying1202 <1452311939@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
